id: PF2D347F2
initial_creation_type: input
source_metadata:
  title: Long-Life Prayers
  language: it
  description: 'A selection of prayers for longevity (zhabs brtan), first more general
    ones, then those for specific individuals (arranged alphabetically by subject):'
  volume:
    d768aafed75a432aa104b278c5be5253:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: General
    1af236b6e5ff4948b667140429c2c645:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: General
    f77f5d4b745740c2bfd74778d45cf02c:
      title: General Long-Life Prayer
      parent: General
    b719b12d550b4b50a16baece683a2cc6:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: General
    169ac8ddd018441bb7497a4f6b2f5269:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Alak Zenkar Rinpoche
    e3ab8fe88901407180761008d703687d:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Alak Zenkar Rinpoche
    46b8444712ef4717afe048a77ef52c83:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Chökyi Nyima Rinpoche
    d58860e7c3124c7b89ac336ab272b6b2:
      title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life
        of Ḍākinī Muntso Rinpoche'
      parent: Ḍākinī Muntso Rinpoche
    577613b5b7424559a4c6af81f133944f:
      title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
      parent: Dezhung Rinpoche
    290ade614cab4ae4bcd7ff9d11004fe7:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Dilgo Khyentse Yangsi Rinpoche
    f9cd1eed108943b2becdc470b01dced0:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Dodrupchen Rinpoche
    8ad8b64bb70c46feaa5355b5c9b8dda2:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Dudjom Rinpoche
    e8048d6053e74aa4a135012e479b2554:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Dzogchen Rinpoche
    908df73a0ed1457f83fd1473b8ab04bf:
      title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
      parent: Dzongsar Khyentse Rinpoche
    1b20e9380c3d4c869db6c8ac16829207:
      title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku
        of Jamyang Khyentse, Thupten Chökyi Gyatso'
      parent: Dzongsar Khyentse Rinpoche
    3a8020ec6d8245e9946ed97d58298386:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Dzongsar Khyentse Rinpoche
    564c68e441154d80a6014db58264f34f:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Fourteenth Dalai Lama
    016433c0f0da44ea958f2415aa4838c4:
      title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His
        Holiness the Dalai Lama'
      parent: Fourteenth Dalai Lama
    f37472f9d06a434faad69bac7217b606:
      title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life
        of His Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One
        by Jamyang Khyentse Chökyi Lodrö'
      parent: Fourteenth Dalai Lama
    8b8484f23dc24978b2882531f6eda8d5:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Fourteenth Dalai Lama
    0e31efee610545548505dc981cfbc044:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Fourteenth Dalai Lama
    58409b9e67784cf39c4a7d0fc2001d9a:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    20e387361cb74d739dd600da32804bd2:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö and Khandro
        Tsering Chödrön
      parent: Jamyang Khyentse Chökyi Lodrö
    007bb030fa0e4561b0c7b5affc19fa65:
      title: 'Sweet Song of Enduring Deathlessness: A Prayer for the Long Life of
        Jamyang Khyentse Chökyi Lodrö'
      parent: Jamyang Khyentse Chökyi Lodrö
    629e6924e8f74049bd605bab4c85077f:
      title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
      parent: Jetsün Lochen Incarnation
    b0c9c5e28023460c80ee1508fe02479f:
      title: Prayer for the Long Life of Khandro Tāre Lhamo
      parent: Khandro Tāre Lhamo
    03034924481d4d31ad3c0edb619359a0:
      title: Prayer for the Long Life of Khandro Tsering Chödrön
      parent: Khandro Tsering Chödrön
    6056caab4d6147bbb69f9444038a4c33:
      title: Prayer for the Long Life of Khyenrab Chökyi Özer
      parent: Khyenrab Chökyi Özer
    25bdc576b5e84d4296720b5a77db4007:
      title: 'The Flower of Auspiciousness: A Prayer for the Long Life of Khenpo Khyenrab
        Chökyi Özer, Masterful Expositor of Scripture and Reasoning'
      parent: Khyenrab Chökyi Özer
    f4d530c7c58c4aa49d7dd13984e9f76d:
      title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long
        Life of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
      parent: Khyenrab Chökyi Özer
    392daa9a01de494fadde9529fe640f61:
      title: Prayer for the Long Life of Lochen Ngawang Chöpal
      parent: Lochen Dharmaśrī
    faad1b1e170442b09affd929cd0f024a:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Lodi Gyari Rinpoche
    3b4e3a9caec14e058c59e52ec915b9bc:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Mayum Tsering Wangmo
    c97e421927c846fb91ad1861389f8dd4:
      title: 'The Drum of Deathlessness: A Prayer for the Long Life of Minling Chung
        Rinpoche'
      parent: Minling Chung Rinpoche
    52450fbf684645e583abbb856455fa85:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Namkhai Norbu Rinpoche
    ac949e79457642eba9e7d0d28e0b3e64:
      title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth
        Incarnation of Terchen Chokgyur Lingpa'
      parent: Neten Chokling Rinpoche
    27b3796b384141828b6410c0d99c6ddc:
      title: Prayer for the Long Life of Orgyen Tobgyal Rinpoche
      parent: Orgyen Tobgyal Rinpoche
    b7ab3af1b7f34859a6b870ca5625fe91:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Patrick Gaffney
    2021e261108f4fed934db9eb729ad9a5:
      title: Prayer for the Long Life of Pema Norbu, Lord of Siddhas
      parent: Penor Rinpoche
    e29816ca552d442691b4e29ac1607d76:
      title: Prayer for the Long Life of Pewar Rinpoche
      parent: Pewar Rinpoche
    729a39cba740403fa0842bfd66b2b97b:
      title: Prayer for the Long Life of the Glorious Sakyapa Father and Son
      parent: Sakya Dagchen and Son
    ecd543726dfc469b98f26a5d21e07411:
      title: A Prayer for the Long Life of Ngawang Kunga Tekchen Palbar Trinlé Wangi
        Gyalpo, the Lord of Refuge and Precious Holder of the Throne of the Drolma
        Palace at Glorious Sakya
      parent: Sakya Trichen
    eb587ed1f03f4d2b92e5c15de08368b8:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Sakya Trichen
    57b2f54481aa472288558e470f4e05f1:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Shechen Rabjam Rinpoche
    18fd1c509edc4eab87435d1660c44c0c:
      title: The Excellent Stream of Nectar of Immortality
      parent: Sogyal Rinpoche
    d3d71aa1fca24d2597d195b50e2c70f9:
      title: Gentle Rain of the Nectar of Immortality
      parent: Sogyal Rinpoche
    eb90ede124324610bf5dae4b3e977820:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Sogyal Rinpoche
    b9f1d316901f4a4784f686ff46dee16f:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Sogyal Rinpoche
    ac071f0fd7d344f6aeb3d5019cfb2491:
      title: The Attainment of Immortality
      parent: Sogyal Rinpoche
    fb7f363fca2b4b0f89518a6988973b6a:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Soktsé Rinpoche
    2f3e886fe4f4450d88a66e701e7d6c53:
      title: 'Padma’s Melodious Song: A Prayer for the Long Life of the Fourth in
        the Succession of Lotus-Tongued Jamchen Tai Situ Incarnations'
      parent: Tai Situ Rinpoche
    b12c90e5f33c48d69671c7ef5aa04e26:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Taklung Tsetrul Rinpoche
    9b4d08bf603d445aade8ad6d46866653:
      title: 'The Sound of the Auspicious Conch: A Prayer for the Long Life of the
        All-Knowing Paṇchen Rinpoche of Tsang'
      parent: Tenth Paṇchen Lama
    4b766406a7d6439fb5d58b9c3f9619ce:
      title: 'The Sweet Song of Māra''s Defeat: A Prayer for the Long Life of the
        Great Tertön and Vidyādhara Lerab Lingpa'
      parent: Tertön Sogyal Lerab Lingpa
    9c6e288fb3d141da9ad4c71a3a7f1954:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Trulshik Rinpoche
    b3ff3ddf55f444d28570dba5a229451b:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Trulshik Rinpoche
    bd557346205849acacce38212ce45c38:
      title: Prayer for the Long Life of Tulku Thondup Rinpoche
      parent: Tulku Thondup Rinpoche
created_at: '2022-03-01T04:19:58.009406'
last_modified_at: '2022-03-01T04:19:58.009410'
